### PR TITLE
Fix Buffer Library

### LINKED ISSUE #211: chrome.remote doesn't work with buffer types
* Electron version: 4.0.1
* Operating system: elementary OS 0.4.1 Loki

There is a problem with the Buffer library export/require. This results in the following error:
```
Uncaught TypeError: Cannot read property 'from' of undefined
    at metaToValue (extensions::remote:209)
    at remoteMemberFunction (extensions::remote:113)
```

### PR DESCRIPTION
**Pull request by stewartlord**
Fix an issue where the buffer library is not exported correctly. Add the original source files for buffer.js and 
its dependencies: base64-js and ieee754. The previous version of buffer.js was pre-compiled and not compatible with Chrome exports.

Fixes #211

### CODE REVIEW

File: lib/util/base64-js.js [hunk 1]
```diff
@@ -0,0 +1,115 @@
+// from: https://github.com/beatgammit/base64-js/releases/tag/v1.2.0
+'use strict'
+
+exports.byteLength = byteLength
```
Comment (bridiver) [inline lib/util/base64-js.js]: this works ok without `$set`?

Comment (stewartlord) [inline lib/util/base64-js.js]: Yup! Would be good to double check that it works for you, but it definitely worked for me.
