### PR TITLE
url fetch requests may outlive the webcontents they are associated with

### LINKED ISSUE #326: crash when url request finishes after webcontents is destroyed
https://stats.brave.com/dashboard#crash/59ce971b6aadc5001df2f57a

### PR DESCRIPTION
**Pull request by bridiver**
fix #326

### CODE REVIEW

File: vendor/brightray/browser/inspectable_web_contents_impl.h [hunk 1]
```diff
@@ -70,6 +69,8 @@ class InspectableWebContentsImpl :
   void UpdateDevToolsZoomLevel(double level);
 
   void WebContentsDestroyed() override;
+
+  void OnURLFetchComplete(const net::URLFetcher* source);
```
Comment (darkdh) [inline vendor/brightray/browser/inspectable_web_contents_impl.h]: Can we friend `FetchDelegate` or everyone can call this public method?

Comment (bridiver) [reply vendor/brightray/browser/inspectable_web_contents_impl.h]: originally I was going to do that, but it's in an anonymous namespace. This class is not going to be around much longer so I'm not too worried about it
