### PR TITLE
don’t crash when wrapper is empty

### LINKED ISSUE #265: crash when no wrapper is available
The root cause of this is not exactly clear, but the behavior or mate::Wrappable is not correct

Crash reason:  EXC_BREAKPOINT / 0x00000002
Crash address: 0x10d4ff35b
Process uptime: 265625 seconds
Thread 0 (crashed)
 0  Brave Framework!mate::WrappableBase::GetWrapper() [wrappable.cc : 24 + 0x1]
    rax = 0x0000000000000000   rdx = 0x0000000000000048
    rcx = 0x0000000000000001   rbx = 0x00007fe242faf8a8
    rsi = 0x00007fe239031400   rdi = 0x00007fe242faf8a8
    rbp = 0x00007fff539d1760   rsp = 0x00007fff539d1760
     r8 = 0x00007fff539d1858    r9 = 0x0000600003e5f074
    r10 = 0x0000600003e5f050   r11 = 0x000060800009c430
    r12 = 0x00007fff539d1778   r13 = 0x00007fe239031400
    r14 = 0x00007fff539d1790   r15 = 0x00007fe2434bb640
    rip = 0x000000010d4ff35b
    Found by: given as instruction pointer in context
 1  Brave Framework!brave::TabViewGuest::WillAttachToEmbedder() [event_emitter.h : 45 + 0x8]
    rbp = 0x00007fff539d17e0   rsp = 0x00007fff539d1770
    rip = 0x000000010c5ba1c6
    Found by: previous frame's frame pointer
 2  Brave Framework!guest_view::GuestViewBase::WillAttach(content::WebContents*, int, bool, base::Callback<void (), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&) [guest_view_base.cc : 564 + 0xc]
    rbp = 0x00007fff539d1840   rsp = 0x00007fff539d17f0
    rip = 0x000000010f3ce89a
    Found by: previous frame's frame pointer
 3  Brave Framework!content::BrowserPluginGuest::Attach(int, content::WebContentsImpl*, BrowserPluginHostMsg_Attach_Params const&) [browser_plugin_guest.cc : 779 + 0x12]
    rbp = 0x00007fff539d18b0   rsp = 0x00007fff539d1850
    rip = 0x000000010c6babf4
    Found by: previous frame's frame pointer

### PR DESCRIPTION
**Pull request by bridiver**
native_mate is deprecated so merging into muon to simplify changes
fix #265

### CODE REVIEW

File: vendor/native_mate/native_mate/wrappable.cc [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+}
+
+WrappableBase::~WrappableBase() {
+  if (!wrapper_.IsEmpty())
+    GetWrapper()->SetAlignedPointerInInternalField(0, nullptr);
+  wrapper_.Reset();
+}
+
+v8::Local<v8::Object> WrappableBase::GetWrapper() {
+  if (!wrapper_.IsEmpty())
```
Comment (bridiver) [inline vendor/native_mate/native_mate/wrappable.cc]: this is the change to native_mate from https://github.com/electron/native-mate/blob/master/native_mate/wrappable.cc#L27

**Comment by darkdh** [comment]
++
